### ISSUE TITLE
LRS Test Frontend: Unhandled error on unauthorized access

### ISSUE THREAD

**Issue by milt** [adlnet-archive/grail-issue-tracker#68]
When I attempt to view my product when not logged in, I get an unhandled 500. Should probably be an auth error/page.

Example URI: https://lrstest.adlnet.gov/products/some-product-id

Returns:
```
TypeError: Cannot read property 'email' of undefined
   at exports.ensureOwner (/home/ubuntu/lrs-test-frontend/products.js:149:31)
   at Layer.handle [as handle_request] (/home/ubuntu/lrs-test-frontend/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/lrs-test-frontend/node_modules/express/lib/router/route.js:131:13)
   at /home/ubuntu/lrs-test-frontend/products.js:167:3
   at Query.<anonymous> (/home/ubuntu/lrs-test-frontend/node_modules/mongoose/lib/model.js:3361:16)
   at /home/ubuntu/lrs-test-frontend/node_modules/kareem/index.js:259:21
   at /home/ubuntu/lrs-test-frontend/node_modules/kareem/index.js:127:16
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by creighton** [comment]
Ok, you have a path that no longer exists in the current version of the test suite. We'll fix this so it gives a better response.

**Comment by creighton** [comment]
Ok should be fixed in https://github.com/adlnet/lrs-test-frontend/commit/86a77d90674cacf55a43520a16db989197ee72a3
